# Generated by Django 2.1.5 on 2019-04-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='distanc',
            new_name='distance',
        ),
    ]
