# Generated by Django 2.1.5 on 2019-03-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0004_auto_20190321_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='iso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='unesco.ISO'),
            preserve_default=False,
        ),
    ]
