# Generated by Django 2.1.5 on 2019-03-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0006_auto_20190321_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.Category'),
        ),
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.Region'),
        ),
        migrations.AlterField(
            model_name='site',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.States'),
        ),
    ]
